
try {
    let b = 10 + a;
} catch ( e ) {
    console.log( b );
} finally {
    console.log( "後続の処理" ); 
}